// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-7299_yrq4tU5RptjSpisd8nQ9HIZ8U',
    appId: '1:991346693109:android:0d19f4fe6f34c5f0a046bc',
    messagingSenderId: '991346693109',
    projectId: 'fir-cli-project-4826e',
    storageBucket: 'fir-cli-project-4826e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgPZEBhYaQ1AINuXUZRwjdQ3SSvVNTIzE',
    appId: '1:991346693109:ios:7b2b3ef0efc037f2a046bc',
    messagingSenderId: '991346693109',
    projectId: 'fir-cli-project-4826e',
    storageBucket: 'fir-cli-project-4826e.firebasestorage.app',
    iosClientId:
        '991346693109-lt6mpala5tatlg1mjs1je0uj95ok8gte.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationsDao',
  );
}
